name             'poise-python'
maintainer       'Harry Cao'
maintainer_email 'hary@area1security.com'
license          'All rights reserved'
description      'Installs/Configures poise-python'
long_description 'Installs/Configures poise-python'
version          '0.1.0'
source_url       'https://github.com/HarryYC/poise-python'
issues_url       'https://github.com/HarryYC/poise-python/issues'
